name: Check clang-format

on:
  workflow_call:

jobs:
  formatting-check:
    name: check ${{ matrix.path['check'] }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: "include"
            exclude: "(rad\\.hpp)"
          - check: "src"
            exclude: ""
          - check: "test"
            exclude: ""
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: "17"
        check-path: ${{ matrix.path['check'] }}
